version: 1.0.{build}-{branch}
image:
  - Visual Studio 2017

install:
  - ps: Install-Product node 8.9.3 x64
build_script:
  - pwsh: ./scripts/ci.ps1

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/7a2944eb6940f46466b9
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Webhook
    url: https://webhooks.gitter.im/e/3a630e02f0eb52bf9f4d
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
