version: 1.0.{build}-{branch}
image:
- Visual Studio 2017
- Visual Studio 2017 Preview
- Visual Studio 2015
- Visual Studio 2013

install:
- ps: Install-Product node 8.9.1 x64
- cmd: npm install --loglevel=error
build_script:
- cmd: npm run vscode:prepublish
- cmd: scripts/prepare_test.bat
test_script:
- cmd: |
    node --version
    scripts/run_tests.bat
    scripts/run_extension_tests.bat
